name: "Update Upstream"

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/update.yaml@b2f3062d20e13e74c038b9dc0d50f9ed9596bc84
    secrets: inherit
